/**
 * Cross-app contracts (PLAN.md, "The source-app contract").
 *
 * Present: scoped entity refs, the shared embedding width, the source-app
 * event contract (inbound events with conversation context, reply-delivery,
 * turn lifecycle, feedback completions, queue/channel names), the internal
 * media + outbound-send API, the operator listing/CRUD API shapes the
 * dashboard aggregates, and the web-chat app's own thread shapes. Landing
 * with later phases: source-status events.
 */
export {
  TOOL_DELIVERY_KEY,
  TURN_META_KEY,
  readToolDelivery,
  readTurnMeta,
  toolDeliveryResult,
  toolDeliverySchema,
  turnMetaEnvelope,
  turnToolMetaSchema,
  type ToolDelivery,
  type TurnToolMeta,
} from "./tool-meta";
export {
  REALTIME_TOPICS,
  type RealtimeEvent,
  type RealtimeTopic,
} from "./realtime";
export {
  contentBucketUnitSchema,
  contentBucketsResponseSchema,
  contentDayCountsResponseSchema,
  contentEmbeddedCountResponseSchema,
  contentHourCountsResponseSchema,
  contentImportRequestSchema,
  contentImportResponseSchema,
  contentIndexClearResponseSchema,
  contentIndexDueResponseSchema,
  contentIndexRowsRequestSchema,
  contentMessageMatchSchema,
  contentMessageSchema,
  contentMessageSeriesResponseSchema,
  contentMessagesResponseSchema,
  contentNewUserSeriesResponseSchema,
  contentReplaceSummariesRequestSchema,
  contentSearchMessagesRequestSchema,
  contentSearchMessagesResponseSchema,
  contentSearchSummariesRequestSchema,
  contentSearchSummariesResponseSchema,
  contentSummariesResponseSchema,
  contentSummaryCountsResponseSchema,
  contentSummarySchema,
  contentTopUsersResponseSchema,
  type ContentBucketUnit,
  type ContentMessage,
  type ContentMessageMatch,
  type ContentSummary,
} from "./content-api";
export { EMBEDDING_DIMENSIONS } from "./embeddings";
export {
  internalDeleteMessageResponseSchema,
  internalEditMenuRequestSchema,
  internalSendFileRequestSchema,
  internalSendMenuRequestSchema,
  internalSendMessageRequestSchema,
  internalSetTitleRequestSchema,
  internalSetTitleResponseSchema,
  internalSendPhotosRequestSchema,
  internalSendVoiceRequestSchema,
  internalSentFileResponseSchema,
  internalSentMenuResponseSchema,
  internalSentMessageResponseSchema,
  internalSentPhotosResponseSchema,
  internalSentVoiceResponseSchema,
  type InternalDeleteMessageResponse,
  type InternalSentFileResponse,
  type InternalSentMessageResponse,
  type InternalSentPhotosResponse,
  type InternalSentVoiceResponse,
} from "./internal-api";
export {
  operatorChatMemberSchema,
  operatorChatMembersResponseSchema,
  operatorChatResponseSchema,
  operatorChatSchema,
  operatorChatUpdateRequestSchema,
  operatorChatsResponseSchema,
  operatorMessageResponseSchema,
  operatorMessageSchema,
  operatorMessagesResponseSchema,
  operatorUserResponseSchema,
  operatorUserSchema,
  operatorUserUpdateRequestSchema,
  operatorUsersResponseSchema,
  type OperatorChat,
  type OperatorChatMember,
  type OperatorMessage,
  type OperatorUser,
} from "./operator-api";
export {
  BUS_EVENTS_CHANNEL,
  INBOUND_MESSAGES_QUEUE,
  addressingSchema,
  assistantDeletedEventSchema,
  chatInfoSchema,
  connectionIdentitySchema,
  conversationContextSchema,
  dashboardRefreshEventSchema,
  eventEnvelopeSchema,
  feedbackRecordedEventSchema,
  historyMessageSchema,
  inboundMessageEventSchema,
  messageMediaSchema,
  participantSchema,
  replyDeliveryEventSchema,
  replyTargetSchema,
  senderInfoSchema,
  sourceIdSchema,
  messageDedupeKey,
  turnCorrelationId,
  turnLifecycleEventSchema,
  type Addressing,
  type AssistantDeletedEvent,
  type ChatInfo,
  type ConnectionIdentity,
  type ConversationContext,
  type DashboardRefreshEvent,
  type EventEnvelope,
  type FeedbackRecordedEvent,
  type HistoryMessage,
  type InboundMessageEvent,
  type MessageMedia,
  type Participant,
  type ReplyDeliveryEvent,
  type ReplyTarget,
  type SenderInfo,
  type TurnLifecycleEvent,
} from "./source-events";
export { CONTRACT_MAJOR } from "./contract-version";
export {
  REF_KINDS,
  SOURCE_ID_PATTERN,
  WEB_CHAT_SOURCE,
  formatScopedRef,
  isScopedRef,
  isSourceId,
  parseScopedRef,
  scopedRef,
  scopedRefSchema,
  tryParseScopedRef,
  type RefKind,
  type ScopedRef,
  type ScopedRefString,
  type SourceId,
} from "./scoped-ref";
export {
  createSourceTraceRecorder,
  sourceTraceEventSchema,
  sourceTraceSchema,
  traceRecordedEventSchema,
  type SourceTrace,
  type SourceTraceClient,
  type SourceTraceRecorder,
  type TraceRecordedEvent,
} from "./trace";
export {
  TRANSPORT_UPDATES_QUEUE,
  messageDeliveredEventSchema,
  transportBotReactionEventSchema,
  transportCallbackRequestSchema,
  transportCallbackResponseSchema,
  transportChatSchema,
  transportEditEventSchema,
  transportMediaSchema,
  transportMessageEventSchema,
  transportMessageLookupResponseSchema,
  transportPresenceEventSchema,
  transportReactionEventSchema,
  transportReceiverSchema,
  transportReplyContextSchema,
  transportUpdateEventSchema,
  transportUserSchema,
  transportConfigChangedEventSchema,
  transportConfigFieldSchema,
  transportDesiredConnectionSchema,
  transportDesiredStateSchema,
  transportRegistrationRequestSchema,
  type MessageDeliveredEvent,
  type TransportBotReactionEvent,
  type TransportCallbackRequest,
  type TransportCallbackResponse,
  type TransportChat,
  type TransportEditEvent,
  type TransportMedia,
  type TransportMessageEvent,
  type TransportMessageLookupResponse,
  type TransportPresenceEvent,
  type TransportReactionEvent,
  type TransportReceiver,
  type TransportReplyContext,
  type TransportUpdateEvent,
  type TransportUser,
  type TransportConfigChangedEvent,
  type TransportConfigField,
  type TransportDesiredConnection,
  type TransportDesiredState,
  type TransportRegistrationRequest,
} from "./transport-events";
