/**
 * Cross-app contracts (PLAN.md, "The source-app contract").
 *
 * Present: scoped entity refs, the shared embedding width, the source-app
 * event contract (inbound events with conversation context, reply-delivery,
 * turn lifecycle, feedback completions, queue/channel names), the internal
 * media + outbound-send API, and the operator listing/CRUD API shapes the
 * dashboard aggregates. Landing with later phases: source-status events.
 */
export { DEFAULT_ASSISTANT_ID } from "./assistants";
export {
  contentDayCountsResponseSchema,
  contentEmbeddedCountResponseSchema,
  contentImportRequestSchema,
  contentImportResponseSchema,
  contentIndexClearResponseSchema,
  contentIndexDueResponseSchema,
  contentIndexRowsRequestSchema,
  contentMessageMatchSchema,
  contentMessageSchema,
  contentMessagesResponseSchema,
  contentReplaceSummariesRequestSchema,
  contentSearchMessagesRequestSchema,
  contentSearchMessagesResponseSchema,
  contentSearchSummariesRequestSchema,
  contentSearchSummariesResponseSchema,
  contentSummariesResponseSchema,
  contentSummaryCountsResponseSchema,
  contentSummarySchema,
  type ContentMessage,
  type ContentMessageMatch,
  type ContentSummary,
} from "./content-api";
export { EMBEDDING_DIMENSIONS } from "./embeddings";
export {
  internalDeleteMessageResponseSchema,
  internalFeedbackPatchRequestSchema,
  internalFeedbackResponseSchema,
  internalFeedbackSchema,
  internalFeedbacksResponseSchema,
  internalMediaDescribeRequestSchema,
  internalMediaDescribeResponseSchema,
  internalMediaResponseSchema,
  internalMediaSchema,
  internalPendingMediaResponseSchema,
  internalRecentMediaResponseSchema,
  internalReactionRequestSchema,
  internalReactionResponseSchema,
  internalSendFileRequestSchema,
  internalSendMessageRequestSchema,
  internalSendPhotosRequestSchema,
  internalSendVoiceRequestSchema,
  internalSentFileResponseSchema,
  internalSentMessageResponseSchema,
  internalSentPhotosResponseSchema,
  internalSentVoiceResponseSchema,
  type InternalDeleteMessageResponse,
  type InternalFeedback,
  type InternalMedia,
  type InternalMediaDescribeResponse,
  type InternalPendingMediaResponse,
  type InternalReactionResponse,
  type InternalSentFileResponse,
  type InternalSentMessageResponse,
  type InternalSentPhotosResponse,
  type InternalSentVoiceResponse,
} from "./internal-api";
export {
  operatorChatResponseSchema,
  operatorChatSchema,
  operatorChatUpdateRequestSchema,
  operatorChatsResponseSchema,
  operatorConnectionCreateRequestSchema,
  operatorConnectionResponseSchema,
  operatorConnectionSchema,
  operatorConnectionUpdateRequestSchema,
  operatorConnectionsResponseSchema,
  operatorMessageResponseSchema,
  operatorMessageSchema,
  operatorMessagesResponseSchema,
  operatorSourceSettingsResponseSchema,
  operatorSourceSettingsSchema,
  operatorSourceSettingsUpdateRequestSchema,
  operatorUserResponseSchema,
  operatorUserSchema,
  operatorUserUpdateRequestSchema,
  operatorUsersResponseSchema,
  type OperatorChat,
  type OperatorConnection,
  type OperatorMessage,
  type OperatorSourceSettings,
  type OperatorUser,
} from "./operator-api";
export {
  BUS_EVENTS_CHANNEL,
  INBOUND_MESSAGES_QUEUE,
  addressingSchema,
  chatInfoSchema,
  connectionIdentitySchema,
  conversationContextSchema,
  dashboardRefreshEventSchema,
  eventEnvelopeSchema,
  feedbackRecordedEventSchema,
  historyMessageSchema,
  inboundMessageEventSchema,
  messageMediaSchema,
  participantSchema,
  replyDeliveryEventSchema,
  replyTargetSchema,
  senderInfoSchema,
  sourceIdSchema,
  turnLifecycleEventSchema,
  type Addressing,
  type ChatInfo,
  type ConnectionIdentity,
  type ConversationContext,
  type DashboardRefreshEvent,
  type EventEnvelope,
  type FeedbackRecordedEvent,
  type HistoryMessage,
  type InboundMessageEvent,
  type MessageMedia,
  type Participant,
  type ReplyDeliveryEvent,
  type ReplyTarget,
  type SenderInfo,
  type TurnLifecycleEvent,
} from "./source-events";
export {
  REF_KINDS,
  SOURCE_IDS,
  formatScopedRef,
  isScopedRef,
  parseScopedRef,
  scopedRef,
  scopedRefSchema,
  tryParseScopedRef,
  type RefKind,
  type ScopedRef,
  type ScopedRefString,
  type SourceId,
} from "./scoped-ref";
